name: Setup
description: Sets up the environment and installs dependencies

runs:
  using: "composite"
  steps:
    - name: Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: false
    - name: Install
      run: pnpm install
      shell: bash
