env:
  browser: true
  es2021: true

plugins:
  - "@typescript-eslint"

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:svelte/recommended"
  - "prettier"

parser: "@typescript-eslint/parser"

overrides:
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"

rules:
  svelte/block-lang:
    - error
    - script:
        - ts

root: true
