name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint:ci
      #- name: Test
      #run: pnpm run test
      - name: Build
        run: pnpm run build:gh-pages
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
